baseURL = "http://technotes.guru"
languageCode = "zh-CN"
title = "TechNotes"
theme = "maupassant"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true



hasCJKLanguage = true
summaryLength = 140

# disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "TechNotes"

[params]
  author = "TechNotes"
  subtitle = "All about technology......"
  keywords = "Java, Spring, Spring boot, Spring cloud, Golang, 微服务, Microservices, Ruby on Rails, DevOps, Agile, 容器化, Docker, K8S, 项目管理, 软件架构"
  description = "专注于IT技术，包括但不限于Java，Spring体系, 微服务, Microservices, 敏捷, Agile, DevOps, 软件架构等"
  busuanzi = false #启用不算子网页统计
  # googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['syntax.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  # customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录
  fancybox = true  # 图片点击放大

## 友情链接，可以多个
# [[params.links]]
#   title = "XXX的博客"
#   name = "XXX的博客"
#   url = "URL Here"

## 侧边栏广告位
# [[params.ads]]
#   title = "【2019双12】ALL IN CLoud 低至1折"
#   url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
#   img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = false
  repo = "cloudhuang/cloudhuang.github.io" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    linenos = true
    style = "monokai"

## 配置网站菜单
[menu]
#   [[menu.main]]
#     identifier = "tools"
#     name = "工具"
#     url = "/tools/"
#     weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4